# Generated by Django 2.0.5 on 2018-05-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=200)),
                ('profile', models.FileField(upload_to='')),
            ],
        ),
    ]
