# Generated by Django 2.0.5 on 2018-05-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='contact',
            new_name='contact_info',
        ),
    ]
