# Generated by Django 2.0.5 on 2018-05-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20180505_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='profile',
            new_name='photo',
        ),
    ]
