# Generated by Django 2.0.5 on 2018-05-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_item_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
