# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-05-10 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
